### ISSUE TITLE
$options pass around every where but not in use

### ISSUE THREAD

**Issue by manwar** [benkasminbullock/File-Versions#1]
Do we need it?

**Comment by benkasminbullock** [comment]
I'll remove this in the next version of the module. Thank you.

**Comment by benkasminbullock** [comment]
It's gone in this commit (accidentally wrote VERSION rather than option):

commit 43e9b17dc6e016f50bae5019e8db8fd3de1b9ddc
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Sun Feb 14 13:58:44 2021 +0900

    Remove old VERSIONS; see also
